-- 코드를 작성해주세요
SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
-- 자기 자신을 2번 받아올 수 있음
FROM ECOLI_DATA A, ECOLI_DATA B
-- 부모와 같은 ID를 가지면서 부모의 형질도 가져야 함.
WHERE A.PARENT_ID = B.ID AND B.GENOTYPE & A.GENOTYPE = B.GENOTYPE
ORDER BY ID ASC